@IsTest public class AccountHandlerTest {
    
    @IsTest public static void testAccountHandler() {
        AccountHandler clsTest = new AccountHandler();
    }

    @IsTest public static void testAccountHandler_2() {
        AccountHandler clsTest = new AccountHandler();
    }

    @IsTest public static void testAccountHandler_3() {
        AccountHandler clsTest = new AccountHandler();
    }

    @IsTest public static void testAccountHandler_4() {
        AccountHandler clsTest = new AccountHandler();
    }

    @IsTest public static void testAccountHandler_5() {
        AccountHandler clsTest = new AccountHandler();
    }

    @IsTest public static void testAccountHandler_6() {
        AccountHandler clsTest = new AccountHandler();
    }
}
